# Generated by Django 5.1.6 on 2025-02-24 05:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحاوية')),
                ('container_type', models.CharField(choices=[('20DC', '20 قدم عادي'), ('40DC', '40 قدم عادي'), ('20RF', '20 قدم مبرد'), ('40RF', '40 قدم مبرد'), ('TANK', 'صهريج')], max_length=4, verbose_name='نوع الحاوية')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (طن)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_description', models.TextField(blank=True, verbose_name='وصف المحتويات')),
                ('status', models.CharField(choices=[('EMPTY', 'فارغة'), ('LOADED', 'محملة'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'تم الإرجاع')], default='EMPTY', max_length=20, verbose_name='حالة الحاوية')),
            ],
            options={
                'verbose_name': 'الحاوية',
                'verbose_name_plural': 'الحاويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإذن')),
                ('issue_date', models.DateTimeField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إذن التسليم',
                'verbose_name_plural': 'أذونات التسليم',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقم', regex='^\\d{11}$')], verbose_name='رقم الهاتف')),
                ('mother_name', models.CharField(max_length=100, verbose_name='اسم الأم')),
                ('governorate', models.CharField(choices=[('BGD', 'بغداد'), ('BSR', 'البصرة'), ('NBL', 'بابل'), ('KRB', 'كربلاء'), ('NJF', 'النجف')], max_length=3, verbose_name='المحافظة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('license_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'السائق',
                'verbose_name_plural': 'السائقين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'رحلات',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('truck_type', models.CharField(choices=[('FLAT', 'مسطحة'), ('CONT', 'حاويات'), ('TANK', 'صهريج')], max_length=4, verbose_name='نوع الشاحنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
            ],
            options={
                'verbose_name': 'الشاحنة',
                'verbose_name_plural': 'الشاحنات',
            },
        ),
        migrations.CreateModel(
            name='TruckDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='سائق رئيسي')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سائق الشاحنة',
                'verbose_name_plural': 'سائقي الشاحنات',
            },
        ),
    ]
