# Generated by Django 5.1.6 on 2025-02-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='truck',
        ),
        migrations.AddField(
            model_name='container',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.driver', verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='container',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='port.truck', verbose_name='الشاحنة'),
        ),
        migrations.AlterField(
            model_name='container',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='port.deliveryorder', verbose_name='إذن التسليم'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='trips', to='port.container', verbose_name='الحاويات'),
        ),
    ]
