# Generated by Django 5.1.6 on 2025-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_remove_trip_driver_remove_trip_truck_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-created_at'], 'verbose_name': 'الشاحنة', 'verbose_name_plural': 'الشاحنات'},
        ),
        migrations.RemoveField(
            model_name='truck',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='model',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_number',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='user',
        ),
        migrations.AddField(
            model_name='truck',
            name='governorate',
            field=models.CharField(choices=[('BGD', 'بغداد'), ('BSR', 'البصرة'), ('NBL', 'بابل'), ('KRB', 'كربلاء'), ('NJF', 'النجف')], default=1, max_length=3, verbose_name='المحافظة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
    ]
