# Generated by Django 5.1.6 on 2025-02-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_truck_options_remove_truck_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_number',
            field=models.CharField(max_length=50),
        ),
    ]
