# Generated by Django 5.1.6 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_alter_container_container_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckDriver',
        ),
    ]
