# Generated by Django 5.1.6 on 2025-02-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_delete_truckdriver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-created_at'], 'verbose_name': 'شاحنة', 'verbose_name_plural': 'الشاحنات'},
        ),
        migrations.AddField(
            model_name='truck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='governorate',
            field=models.CharField(choices=[('BGD', 'بغداد'), ('BSR', 'البصرة'), ('NBL', 'بابل'), ('KRB', 'كربلاء'), ('NJF', 'النجف')], max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(choices=[('FLAT', 'مسطحة'), ('CONT', 'حاويات'), ('TANK', 'صهريج')], max_length=50, verbose_name='نوع الشاحنة'),
        ),
    ]
