# Generated by Django 5.1.6 on 2025-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_alter_truck_options_truck_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='permission_status',
            field=models.CharField(choices=[('loading', 'تحميل'), ('empty', 'فارغ'), ('general_goods', 'بضائع عامة'), ('partial', 'تجزئة')], default='loading', max_length=20, verbose_name='حالة الإذن'),
        ),
    ]
