# Generated by Django 5.1.6 on 2025-02-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_deliveryorder_permission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='truck',
        ),
    ]
