# Generated by Django 5.1.6 on 2025-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0009_remove_deliveryorder_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'فارغة'), ('LOADED', 'محملة'), ('GENERAL_GOODS', 'بضائع عامة'), ('PARTIAL', 'تجزئة')], default='EMPTY', max_length=20, verbose_name='حالة الحاوية'),
        ),
    ]
