# Generated by Django 5.1.6 on 2025-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0010_alter_container_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='permission_status',
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('EMPTY', 'فارغة'), ('LOADED', 'محملة'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'تم الإرجاع')], default='EMPTY', max_length=20, verbose_name='حالة الحاوية'),
        ),
    ]
