# Generated by Django 5.1.6 on 2025-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_remove_deliveryorder_permission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('LOADING', 'تحميل'), ('EMPTY', 'فارغ'), ('GENERAL_CARGO', 'بضائع عامة'), ('UNLOADING', 'تفريغ')], default='LOADING', max_length=20, verbose_name='الحالة'),
        ),
    ]
