# Generated by Django 5.1.6 on 2025-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0012_alter_deliveryorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('LOADING', 'تحميل'), ('EMPTY', 'فارغ'), ('GENERAL_CARGO', 'بضائع عامة'), ('UNLOADING', 'تجزئة')], default='LOADING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('LOADING', 'تحميل'), ('EMPTY', 'فارغ'), ('GENERAL_CARGO', 'بضائع عامة'), ('UNLOADING', 'تجزئة')], default='LOADING', max_length=20, verbose_name='الحالة'),
        ),
    ]
