# Generated by Django 5.1.6 on 2025-02-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_alter_container_status_alter_deliveryorder_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='unique_delivery_order_trip',
        ),
    ]
