# Generated by Django 5.1.6 on 2025-02-26 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0014_remove_trip_unique_delivery_order_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('delivery_order',), name='unique_delivery_order_trip'),
        ),
    ]
