# Generated by Django 5.1.6 on 2025-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_trip_unique_delivery_order_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الرخصة'),
        ),
    ]
