# Generated by Django 5.1.6 on 2025-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'رحلة', 'verbose_name_plural': 'رحلات'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='trips', to='port.container'),
        ),
    ]
