# Generated by Django 5.1.6 on 2025-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_alter_trip_options_alter_trip_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
