# Generated by Django 5.1.6 on 2025-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_driver_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم السائق'),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck_plate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم لوحة الشاحنة'),
        ),
    ]
