# Generated by Django 5.1.6 on 2025-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_trip_driver_name_trip_truck_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الحجم'),
        ),
    ]
